{
 "title": "机房UPS监控",
 "description": "huawei ups 监控",
 "tags": [
  "snmp",
  "zabbix",
  "ups"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "group", "query": "动环监控" },
   {
    "name": "host",
    "label": "主机",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center; vertical-align: middle;\">\r\n<img src=\"http://192.168.0.154:3000/public/css/huawei.png?raw=true\" style=\"background-color:white\" height=\"125\" alt=\"APC\"/>\r\n</p>"
   }
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT \"sysUpTime\"  / 100 FROM \"snmp.UPS\" WHERE (\"agent_host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "温度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host (fahrenheit)",
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "UPS device temperature" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT mean(\"upsAdvBatteryTemperature\") * 9/5 + 32 FROM \"snmp.UPS\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\", \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "upsAdvBatteryTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "UPS 负载",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Output load" },
     "itemTag": { "filter": "component: output" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "设备型号",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "System name" },
     "itemTag": { "filter": "component: system" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvTestDiagnosticSchedule" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "工作模式",
   "type": "stat",
   "description": "ups 工作模式",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Power supply method" },
     "itemTag": { "filter": "component: power" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvInputLineFailCause" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "UPS 状态",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "UPS ctrl power State" },
     "itemTag": { "filter": "component: health" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsBasicOutputStatus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "SNMP agent availability" },
     "itemTag": { "filter": "component: health" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvTestDiagnosticsResults" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "电池容量",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Battery capacity" },
     "itemTag": { "filter": "component: battery" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvBatteryCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "电池后备时间",
   "type": "stat",
   "description": "电池后备时间，切换为电池供电，才可查看对应时间",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Battery backup time" },
     "itemTag": { "filter": "component: battery" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsBasicBatteryTimeOnBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "电池状态",
   "type": "stat",
   "description": "Indicates whether the UPS batteries need replacing.",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Battery status" },
     "itemTag": { "filter": "component: battery" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvBatteryReplaceIndicator" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "告警",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "UPS alarm curr num" },
     "itemTag": { "filter": "component: health" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvBatteryRunTimeRemaining" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "市电电压",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Input voltage" },
     "itemTag": { "filter": "component: input" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IN/OUT 电压",
   "type": "timeseries",
   "description": "输入输出电压",
   "gridPos": { "h": 8, "w": 18, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_agent_host (input)",
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Input voltage" },
     "itemTag": { "filter": "component: input" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvInputLineVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "- 1" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "alias": "$tag_agent_host (input)",
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Output voltage" },
     "itemTag": { "filter": "component: output" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvInputLineVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "- 1" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "输出电压",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:86",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/(Output voltage)/",
        "输出电压"
       ],
       "text": "replaceAlias(/(Output voltage)/, 输出电压)"
      },
      {
       "$$hashKey": "object:87",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/($host:)/",
        " "
       ],
       "text": "replaceAlias(/($host:)/,  )"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Output voltage" },
     "itemTag": { "filter": "component: output" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "市电频率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Input frequency" },
     "itemTag": { "filter": "component: input" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "输出电流",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Output current" },
     "itemTag": { "filter": "component: output" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "电池电压",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Battery voltage" },
     "itemTag": { "filter": "component: battery" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "输出功率/负载",
   "type": "timeseries",
   "description": "输出功率/负载",
   "gridPos": { "h": 8, "w": 18, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_agent_host (watt)",
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Output Active Power" },
     "itemTag": { "filter": "component: output" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "alias": "$tag_agent_host (watt)",
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$host" },
     "item": { "filter": "Output load" },
     "itemTag": { "filter": "component: output" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "输出功率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Output Active Power" },
     "itemTag": { "filter": "component: output" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "电池电流",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Battery current" },
     "itemTag": { "filter": "component: battery" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "输出频率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Output frequency" },
     "itemTag": { "filter": "component: output" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "告警详情",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}